# cryptmail.rb configuration file

interval:
  hours: 0
  minutes: 1
  seconds: 0

pop:
  host: pop.mailhost.com
  port: 110
  user: username
  password: password
  
smtp:
  host: smtp.mailhost.com
  port: 25
  user: username
  password: password

storage:
  new: /var/cryptmail/incoming
  processed: /var/cryptmail/processed
  attachments: /var/cryptmail/attachments

reply:
  user_agent: cryptmail.rb GnuPG Mailer
  from: GnuPG Encryption-Test Service <username@mailhost.com>
  subject: GnuPG Encryption Test
  message: "Your message was decrypted sucessfully. Here is my reply.\nIf you can see this, you've set up GnuPG and your mailclient successfully!"
  
allowed_content_types:
  - application/pgp-keys
  - application/octet-stream
  - text/plain